//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenPgp.FluentApi.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenPgp.FluentApi.UnitTest.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PGP PRIVATE KEY BLOCK-----
        ///
        ///lQPGBFtRGh0BCAChhTwK+MlR+5o9PkWcEyeXOlbXbHqX5NAjFy/IOq5iCFTBv+As
        ///zslqddOrJG6buuWx+RZkwPT9KvWl1P2B8fOLqEMBHalPAUZEGsO5lUteUa/mMG5O
        ///U0hz7DbJ/rk3Pt37CjtHDqIjEsD+eAX/jVT/5vJ7Z0Zjj6fH/eCOKhiHC+Z0dYwO
        ///2o1hB5ZsgW7TvOG+3p9x0EcdD2pg4/Tb7TGLKAXIL5J7w8x7n4Xv+Jv0LF6b3zH6
        ///QBHCq27AX438afD8uV9xH53rmR28cJ75TPHjP50upMmpUsTnTRQiRngZkB68CbwE
        ///EArVjWk7cpMS9T9VuRCr1xwFqfGp2PhQYIXLABEBAAH+BwMCKLiQsexpXYvDJ7QO
        ///fbrqzrRijWyrPZGKSmduiUWiksrLLVO0iD34kL9XiejGlNFnsAlxhEh+jWV3HMAr
        ///WcfqPOKxS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey1 {
            get {
                return ResourceManager.GetString("PrivateKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PGP PRIVATE KEY BLOCK-----
        ///
        ///lQPGBFtRGkQBCADQ6BM819j8lkMz1zrNOoUOJsVrZMJbTg+0pxWn8zvIQ/cc91/q
        ///HNlc7kjr7rmLC0EysvUl+bGGNbPyGyxgWcGU03vNXGR8xS45xSaVxArCS51E3tPw
        ///SaYQZm9AhuJ4RXRwg+HzgivLjuFAzquyK6gxEukqig+vdoXYJuHN5N2bhYuXnMNB
        ///mGsuyB9HF3EGdu+L0uZQqaadtlLnezUWUNuOQJ7C+rdqqfSZM9IKPc4tJ6NGME+g
        ///vA9Hfu+Ujje7gyEOa9TTZk4HdRJQTsKa408X8o7TH02REJB2q84hh4L1b+pinJWH
        ///rGdqT7hetsuqyGYaXz7YFCuWunUQ2fU0lpMLABEBAAH+BwMC2TZ4XoDvS+rD0f0n
        ///kgKrCL1AyPulP1DmA3GqcgHkOPjV4yFkaed+gxxbgaQujCH6s83k/hDeQbQT35GV
        ///2IPCFvhwQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey2 {
            get {
                return ResourceManager.GetString("PrivateKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PGP PUBLIC KEY BLOCK-----
        ///
        ///mQENBFtRGh0BCAChhTwK+MlR+5o9PkWcEyeXOlbXbHqX5NAjFy/IOq5iCFTBv+As
        ///zslqddOrJG6buuWx+RZkwPT9KvWl1P2B8fOLqEMBHalPAUZEGsO5lUteUa/mMG5O
        ///U0hz7DbJ/rk3Pt37CjtHDqIjEsD+eAX/jVT/5vJ7Z0Zjj6fH/eCOKhiHC+Z0dYwO
        ///2o1hB5ZsgW7TvOG+3p9x0EcdD2pg4/Tb7TGLKAXIL5J7w8x7n4Xv+Jv0LF6b3zH6
        ///QBHCq27AX438afD8uV9xH53rmR28cJ75TPHjP50upMmpUsTnTRQiRngZkB68CbwE
        ///EArVjWk7cpMS9T9VuRCr1xwFqfGp2PhQYIXLABEBAAG0E3Rlc3QxIDx0ZXN0MUB0
        ///ZXN0MT6JAU4EEwEIADgWIQSm+HET0YWAYnzSNP9mfwJ0aT+ZDwUCW1EaHQIbAwUL
        ///CQgHAgYVCg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublicKey1 {
            get {
                return ResourceManager.GetString("PublicKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PGP PUBLIC KEY BLOCK-----
        ///
        ///mQENBFtRGkQBCADQ6BM819j8lkMz1zrNOoUOJsVrZMJbTg+0pxWn8zvIQ/cc91/q
        ///HNlc7kjr7rmLC0EysvUl+bGGNbPyGyxgWcGU03vNXGR8xS45xSaVxArCS51E3tPw
        ///SaYQZm9AhuJ4RXRwg+HzgivLjuFAzquyK6gxEukqig+vdoXYJuHN5N2bhYuXnMNB
        ///mGsuyB9HF3EGdu+L0uZQqaadtlLnezUWUNuOQJ7C+rdqqfSZM9IKPc4tJ6NGME+g
        ///vA9Hfu+Ujje7gyEOa9TTZk4HdRJQTsKa408X8o7TH02REJB2q84hh4L1b+pinJWH
        ///rGdqT7hetsuqyGYaXz7YFCuWunUQ2fU0lpMLABEBAAG0E3Rlc3QyIDx0ZXN0MkB0
        ///ZXN0Mj6JAU4EEwEIADgWIQR//AoaKfeQPEYY8hMK+fs3lkS+pgUCW1EaRAIbAwUL
        ///CQgHAgYVCg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublicKey2 {
            get {
                return ResourceManager.GetString("PublicKey2", resourceCulture);
            }
        }
    }
}
