name: .NET Core

on:
  push:
    branches: [ release/1.2 ]
  pull_request:
    branches: [ release/1.2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
       PROJECT_FILE_PATH: Org.BouncyCastle.Bcpg.OpenPgp.FluentApi/Org.BouncyCastle.Bcpg.OpenPgp.FluentApi.csproj  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
      
